### PR TITLE
Fix for integrated speakers not working

### PR DESCRIPTION
**Pull request by gvlasov**
My speakers weren't working on Lenovo Legion 7i Pro, have been looking for a solution for two days and finally found one. Have to share it with the community

### CODE REVIEW

**Comment by gvlasov** [comment]
All thanks to the glorious @edkirin

**Comment by gvlasov** [comment]
Nope, wasn't that.

This seems to have helped though: https://www.reddit.com/r/LenovoLegion/comments/12752y7/comment/kg2uv27/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by edkirin** [comment]
> All thanks to the glorious @edkirin

Btw, it wasn't me who found the solution. I referenced to [source](https://forums.lenovo.com/t5/Ubuntu/Ubuntu-and-legion-pro-7-16IRX8H-audio-issues/m-p/5210709?page=32#6364374) in my post.

**Comment by gvlasov** [comment]
@edkirin I wonder in what cases does power saving fix works, and in what cases you just need to update the firmware.

And it still doesn't fix missing sound on Windows with every part of its sound system working fine. I guess Windows installs its own broken firmware on boot?

**Comment by cszach** [comment]
Thank you! 🧡

**Comment by gvlasov** [comment]
This ultimately didn't work for me, still without speakers sound, but this solution is better:

https://github.com/trgeiger/tas2781-fix-16IRX8H

It doesn't automate the sound issue fix, but at least I have consistent success with its manual activaton.
Some people report that linux kernel 6.12-rc fixes the sound issue, but it didn't work for me either.

**Pull request merged**
